security:
    encoders:
        
        App\Entity\Users:
            algorithm: auto

    providers:

        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email
    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: security:app:logout

    access_control:
        - { path: ^/login$,                 roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$,              roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgotten-password$,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,                       roles: ROLE_USER }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
